name: advanced_tips
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  analyzer: ^3.4.1
  carousel_slider: ^4.1.1
  connectivity: ^3.0.6
  country_code_picker: ^2.0.2
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^4.0.6
  easy_localization: ^3.0.0
  flutter:
    sdk: flutter
  flutter_phoenix: ^1.0.0
  flutter_svg: ^1.0.3
  freezed: ^1.1.1
  get_it: ^7.2.0
  image_picker: ^0.8.5
  internet_connection_checker: ^0.0.1+3
  json_serializable: ^6.1.5
  lottie: ^1.2.2
  palestine_console: ^0.0.10
  pretty_dio_logger: ^1.1.1
  retrofit: ^3.0.1+1
  rxdart: ^0.27.3
  shared_preferences: ^2.0.13
  smooth_page_indicator: ^1.0.0+2

dev_dependencies:
  build_runner: ^2.1.8
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  retrofit_generator: ^4.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/json/
    - assets/translations/ar-SA.json
    - assets/translations/en-US.json

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
